# Default values for rsyncd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: jenkinsciinfra/rsyncd
  tag: 1.0.26
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podSecurityContext: {}
# fsGroup: 2000
containerSecurityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
# (privately exposed) port of the pod. Should be > 1024 as the container should run as non root
port: 1873
service:
  type: ClusterIP
  # Port published by the "Service". Maps to the pod (privately exposed) port
  port: 873
  # LoadBalancerIP: 1.2.3.4
  whitelisted_sources: []
  # - 52.167.253.43/32
  # - 52.202.51.185/32
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
configuration:
  motd:
    path: /etc/rsyncd.d/jenkins.motd
    content: |-
      ========================
      ==== JENKINS MIRROR ====
      ========================

      **Read Only**

      Feel free to reach out on https://www.jenkins.io/chat/#jenkins-infra/ with any question you may have
  ## Uncomment to specify a list of "rsyncd" components (rsync://server.name:873/COMPONENT)
  components: []
  #   - name: jenkins
  #     path: /rsyncd/data/jenkins
  #     comment: "Jenkins Read-Only Mirror"
  #     volume:
  #       emptyDir: {}
