apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: rating
type: application
version: 0.5.1
maintainers:
- email: jenkins-infra-team@googlegroups.com
  name: jenkins-infra-team
