apiVersion: v2
version: 0.4.16
appVersion: 0.10.60
description: plugin-site-issues
name: plugin-site-issues
type: application
maintainers:
- email: jenkins-infra-team@googlegroups.com
  name: jenkins-infra-team
