apiVersion: v1
description: A Helm chart for accounts.jenkins.io
maintainers:
- email: jenkins-infra-team@googlegroups.com
  name: jenkins-infra-team
name: accountapp
version: 0.10.22
appVersion: 0.6.82
