apiVersion: v1
description: Mirrobits helm chart for Kubernetes
name: mirrorbits
version: 5.10.4
appVersion: "v0.6.1"
maintainers:
- email: jenkins-infra-team@googlegroups.com
  name: jenkins-infra-team
