apiVersion: v1
appVersion: v0.5.2
description: Mirrobits helm chart for Kubernetes
maintainers:
- email: jenkins-infra-team@googlegroups.com
  name: jenkins-infra-team
name: mirrorbits
version: 1.1.11
