apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "artifact-caching-proxy.fullname" . }}
  labels:
    {{- include "artifact-caching-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "artifact-caching-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        checksum/default-config: {{ include (print $.Template.BasePath "/nginx-default-configmap.yaml") . | sha256sum }}
        checksum/proxy-config: {{ include (print $.Template.BasePath "/nginx-proxy-configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "artifact-caching-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.initContainer.enabled }}
      initContainers:
      - name: permission-fix
        image: busybox
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command: ['sh', '-c']
        args: ["chown -Rv {{ .Values.initContainer.chownArgs }}  {{ .Values.paths.cachePath }} && ls -l {{ .Values.paths.cachePath }}"]
        volumeMounts:
          - mountPath: {{ .Values.paths.cachePath }}
            name: nginx-cache
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: nginx-default-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-proxy-config
            mountPath: /etc/nginx/conf.d/
          - name: nginx-health-config
            mountPath: "{{ .Values.paths.wwwPath }}{{ .Values.paths.healthPath }}"
          - name: nginx-tmp
            mountPath: /var/tmp/
          - name: nginx-cache
            mountPath: {{ .Values.paths.cachePath }}
      volumes:
      - name: nginx-default-config
        configMap:
          name: {{ include "artifact-caching-proxy.fullname" . }}-default-configmap
      - name: nginx-proxy-config
        configMap:
          name: {{ include "artifact-caching-proxy.fullname" . }}-proxy-configmap
      - name: nginx-health-config
        configMap:
          name: {{ include "artifact-caching-proxy.fullname" . }}-health-configmap
      - name: nginx-tmp
        emptyDir: {}
      - name: nginx-cache
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "artifact-caching-proxy.fullname" . }}-pvc
      {{- else }}
        emptyDir: {}
      {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
