apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artifact-caching-proxy.fullname" . }}-default-configmap
  labels: {{ include "artifact-caching-proxy.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    # The following line is the only change from the original nginx.conf from the official nginx image
    pid        /var/tmp/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent $request_time "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"'
                          '"$upstream_addr" "$upstream_status" "$upstream_response_time"';

        access_log  /var/log/nginx/access.log  main;

        # Optimize IO workload for static files
        # https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/#enabling-sendfile
        # https://www.sobyte.net/post/2022-08/nginx-send/
        sendfile        on;
        sendfile_max_chunk 1m; # Limits chunks to 1 Megabytes;
        tcp_nopush     on;

        keepalive_timeout  65;

        gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
