{{- if eq .Values.templateType "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "artifact-caching-proxy.fullname" . }}
  labels:
    {{- include "artifact-caching-proxy.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "artifact-caching-proxy.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "artifact-caching-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "artifact-caching-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort:  {{ .Values.service.port }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: nginx-default-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-proxy-config
          mountPath: /etc/nginx/conf.d/
        - name: nginx-tmp
          mountPath: /var/tmp/
        - name: nginx-cache
          mountPath: {{ .Values.cache.path }}
      volumes:
      - name: nginx-default-config
        configMap:
          name: {{ include "artifact-caching-proxy.fullname" . }}-default-configmap
      - name: nginx-proxy-config
        configMap:
          name: {{ include "artifact-caching-proxy.fullname" . }}-proxy-configmap
      - name: nginx-tmp
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: nginx-cache
    spec:
      storageClassName: {{ .Values.persistence.storageClass }}
      accessModes:
      - {{ .Values.persistence.accessMode }}
      resources:
        requests:
          storage: "{{ .Values.persistence.size }}Gi"
{{- end }}
