---
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for serving website with nginx
name: nginx-website
maintainers:
- email: jenkins-infra-team@googlegroups.com
  name: jenkins-infra-team
version: 0.3.1
